## Perceptron
### **m** input features and **n** output results

### Import modules

In [1]:
import numpy as np
from perceptron import Perceptron

### Define training set #1

In [2]:
training_set = [
    ([0.0, 1.0, 1.0], [0.0, 0.0]),
    ([1.0, 0.0, 0.0], [1.0, 1.0]),
    ([0.5, 0.5, 0.5], [1.0, 1.0])
]

### Define training set #2
* Feature 1: sweatnest of the wine
* Feature 2: acidity of the wine
* Feature 3: power of wine

Result: 1 good 0 not good

In [2]:
training_set = [
    ([0.0, 1.0, 1.0], [0.0]),
    ([1.0, 0.0, 0.0], [1.0]),
    ([0.5, 0.5, 0.5], [1.0])
]

### Perceptron learning


In [3]:
perceptron = Perceptron(training_set)
print("Initial weights: \n", perceptron.weights)
perceptron.learning()
print("Learnt weights: \n", perceptron.weights)


Initial weights: 
 [[ 0.06998944 -2.74489859 -0.08899375  0.36449898]]
Learnt weights: 
 [[-1.13001056 -0.64489859 -0.98899375 -0.53550102]]


### Define input vector and run perceptron

In [7]:
net_input = [1.0, 0.0, 0.0]
output = perceptron.run([net_input])
print("Output for ", net_input, " is ", output)

Output for  [1.0, 0.0, 0.0]  is  [1]


### Save weight matrix on the disk

In [5]:
np.save('weight_matrix', perceptron.weights)

### Create new perceptron net a set its weights from disk

In [6]:
perceptron = Perceptron(training_set)
print("Initial weights: \n", perceptron.weights)
perceptron.weights = np.load('weight_matrix.npy')
print("Learnt weights: \n", perceptron.weights)

Initial weights: 
 [[ 1.14791268 -0.8789867  -0.67030694  0.93702913]]
Learnt weights: 
 [[-1.13001056 -0.64489859 -0.98899375 -0.53550102]]
