## Perceptron
### **m** input features and **n** output results

### Import modules

In [1]:
import numpy as np
import pandas as pd
from perceptron import Perceptron

### Define training set #1

In [2]:
training_set = [
    ([0.0, 1.0, 1.0], [0.0, 0.0]),
    ([1.0, 0.0, 0.0], [1.0, 1.0]),
    ([0.5, 0.5, 0.5], [1.0, 1.0])
]

### Define training set #2
* Feature 1: sweetness of the wine
* Feature 2: acidity of the wine
* Feature 3: power of wine

Result: 1 good 0 not good

In [2]:
training_set = [
    ([0.0, 1.0, 1.0], [0.0]),
    ([1.0, 0.0, 0.0], [1.0]),
    ([0.5, 0.5, 0.5], [1.0])
]

### Perceptron learning


In [3]:
perceptron = Perceptron(training_set)
print("Initial weights: \n", perceptron.weights)
perceptron.learning()
print("Learnt weights: \n", perceptron.weights)


Initial weights: 
 [[ 0.06998944 -2.74489859 -0.08899375  0.36449898]]
Learnt weights: 
 [[-1.13001056 -0.64489859 -0.98899375 -0.53550102]]


### Define input vector and run perceptron

In [7]:
net_input = [1.0, 0.0, 0.0]
output = perceptron.run([net_input])
print("Output for ", net_input, " is ", output)

Output for  [1.0, 0.0, 0.0]  is  [1]


### Save weight matrix on the disk

In [5]:
np.save('weight_matrix', perceptron.weights)

### Create new perceptron net a set its weights from disk

In [6]:
perceptron = Perceptron(training_set)
print("Initial weights: \n", perceptron.weights)
perceptron.weights = np.load('weight_matrix.npy')
print("Learnt weights: \n", perceptron.weights)

Initial weights: 
 [[ 1.14791268 -0.8789867  -0.67030694  0.93702913]]
Learnt weights: 
 [[-1.13001056 -0.64489859 -0.98899375 -0.53550102]]


### Using Excel Table to define training set

### Wines Excel file

In [21]:
data = pd.read_excel('wines.xlsx')
data.head()
training_set = []
for index, row in data.iterrows():
    features = [row['Sweetness'], row['Acidity'], row['Power']]
    result = [row['Good']]
    training_set.append((features, result))
#print("Transformations: ", training_set)
training_set



[([0.0, 1.0, 1.0], [0.0]), ([1.0, 0.0, 0.0], [1.0]), ([0.5, 0.5, 0.5], [1.0])]

### Diagnosis learning verification

In [2]:
data = pd.read_excel('diagnosis.xlsx')
data.head()
training_set = []
for index, row in data.iterrows():
    features = [row['Fever'], row['Cough'], row['Headache'], row['Tiredness'], row['Night Sweat']]
    result = [row['Pneumonia'], row['Flu'], row['Cold']]
    training_set.append((features, result))

perceptron = Perceptron(training_set)
perceptron.learning()

for row in training_set:
    net_input = row[0]
    net_output = perceptron.run(net_input)
    print("Input: ", net_input, " Output: ", net_output)

header = list(data.columns)
 

Input:  [0.0, 0.5, 0.5, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 1.0, 1.0, 1.0, 0.0]  Output:  [0, 1, 0]
Input:  [0.5, 1.0, 0.0, 1.0, 1.0]  Output:  [1, 0, 0]
Input:  [0.0, 0.5, 0.0, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 0.5, 1.0, 0.5, 0.0]  Output:  [0, 1, 0]
Input:  [1.0, 1.0, 0.0, 0.5, 0.5]  Output:  [1, 0, 0]


### Usage of diagnosis app

In [5]:
input_data = pd.read_excel('diagnosis_input.xlsx')
input_data.head()
input_set = []
for index, row in input_data.iterrows():
    features = [row['Fever'], row['Cough'], row['Headache'], row['Tiredness'], row['Night Sweat']]
    input_set.append(features)

output_set = []
for net_input in input_set:
    net_output = perceptron.run(net_input)
    output_set.append(net_output)
    print("Input: ", net_input, " Output: ", net_output)
# Create a DataFrame for the output data

header = list(data.columns)
output_data = pd.DataFrame(columns=header)

for i in range(len(input_set)):
    row = input_set[i] + output_set[i]
    output_data.loc[i] = row

output_data.to_excel('diagnosis_output.xlsx', index=False)
output_data



Input:  [0.0, 0.5, 0.0, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 1.0, 1.0, 1.0, 0.0]  Output:  [0, 1, 0]
Input:  [0.5, 1.0, 0.0, 1.0, 1.0]  Output:  [1, 0, 0]
Input:  [1.0, 0.5, 0.5, 0.5, 0.0]  Output:  [1, 0, 0]
Input:  [0.0, 0.5, 0.0, 0.2, 0.0]  Output:  [0, 0, 1]


Fever  Cough  Headache  Tiredness  Night Sweat  Pneumonia  Flu  Cold
0    0.0    0.5       0.0        0.0          0.0        0.0  0.0   1.0
1    1.0    1.0       1.0        1.0          0.0        0.0  1.0   0.0
2    0.5    1.0       0.0        1.0          1.0        1.0  0.0   0.0
3    1.0    0.5       0.5        0.5          0.0        1.0  0.0   0.0
4    0.0    0.5       0.0        0.2          0.0        0.0  0.0   1.0